let dados = [
  {
    id: 1,
    titulo: 'Casa de Ferragens Nova Europa',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Loja completa de ferramentas e materiais para construção. Atendimento especializado e variedade de produtos para profissionais e domésticos.',
    tags: ['ferramentas', 'construção', 'loja'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 99999-1234',
    badge: 'Melhor Preço',
  },
  {
    id: 2,
    titulo: 'Marmoraria Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Especializada em mármore e granito para cozinhas, banheiros e áreas externas. Orçamento rápido e atendimento na região.',
    tags: ['mármore', 'granito', 'reforma'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 98888-4321',
    badge: 'Destaque',
  },
  {
    id: 3,
    titulo: 'Agro Jardim & Irrigação',
    cat: 'Comércio',
    preco: 'A partir de R$ 50,00',
    desc: 'Venda de mangueiras, ferramentas de jardim, adubos e acessórios para irrigação. Ideal para cuidar do seu quintal.',
    tags: ['jardim', 'irrigação', 'plantas'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 97777-5555',
    badge: 'Numero Um',
  },
  {
    id: 4,
    titulo: 'FixaTudo Ferragens',
    cat: 'Comércio',
    preco: 'A partir de R$ 20,00',
    desc: 'Parafusos, grampos, ferramentas e acessórios para manutenção e montagem. Produtos novos e seminovos.',
    tags: ['ferragens', 'bancada', 'manutenção'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 96666-7777',
    badge: 'Usado',
  },
  {
    id: 5,
    titulo: 'Livraria Técnica Campinas',
    cat: 'Comércio',
    preco: 'A partir de R$ 30,00',
    desc: 'Livros técnicos de elétrica, construção e manutenção. Ideal para estudantes e profissionais da área.',
    tags: ['livro', 'elétrica', 'técnico'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 95555-2222',
    badge: '',
  },
  {
    id: 6,
    titulo: 'Serviços Rápidos Nova Europa',
    cat: 'Serviços',
    preco: 'A partir de R$ 80/h',
    desc: 'Serviços de marido de aluguel: elétrica, hidráulica, pintura e montagem de móveis. Atendimento rápido no bairro.',
    tags: ['reparos', 'pintura', 'hidráulica'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 94444-3333',
    badge: '',
  },
  {
    id: 7,
    titulo: 'Padaria Nova Europa',
    cat: 'Comércio',
    preco: 'A partir de R$ 5,00',
    desc: 'Pães frescos, bolos, salgados e café da manhã completo. Atendimento rápido e ambiente familiar.',
    tags: ['padaria', 'café', 'pães'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 93333-1111',
    badge: 'Popular',
  },
  {
    id: 8,
    titulo: 'Mercado Boa Compra',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Mercado de bairro com hortifruti fresco, açougue e mercearia completa. Entregas na região.',
    tags: ['mercado', 'alimentos', 'delivery'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 92222-2222',
    badge: '',
  },
  {
    id: 9,
    titulo: 'Auto Elétrica Nova Europa',
    cat: 'Serviços',
    preco: 'A partir de R$ 100,00',
    desc: 'Serviços elétricos automotivos, bateria, alternador e diagnóstico completo.',
    tags: ['carro', 'elétrica', 'automotivo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-3333',
    badge: '',
  },
  {
    id: 10,
    titulo: 'Salão Beleza & Estilo',
    cat: 'Serviços',
    preco: 'A partir de R$ 30,00',
    desc: 'Cortes, escova, coloração e tratamentos capilares. Atendimento com hora marcada.',
    tags: ['beleza', 'cabelo', 'salão'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 94444-1111',
    badge: '',
  },
  {
    id: 11,
    titulo: 'Pet Shop Amigo Fiel',
    cat: 'Comércio',
    preco: 'A partir de R$ 20,00',
    desc: 'Rações, acessórios e banho e tosa para seu pet. Atendimento com carinho e qualidade.',
    tags: ['pet', 'ração', 'banho'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 95555-3333',
    badge: '',
  },
  {
    id: 12,
    titulo: 'Farmácia Vida Mais',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Medicamentos, produtos de higiene e perfumaria. Atendimento rápido e preços acessíveis.',
    tags: ['farmácia', 'saúde', 'remédios'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 96666-1111',
    badge: '24h',
  },
  {
    id: 13,
    titulo: 'Lanchonete Sabor Caseiro',
    cat: 'Comércio',
    preco: 'A partir de R$ 15,00',
    desc: 'Lanches, porções e refeições rápidas com sabor de comida caseira.',
    tags: ['lanche', 'comida', 'rápido'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 97777-1111',
    badge: '',
  },
  {
    id: 14,
    titulo: 'Oficina Mecânica Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Manutenção geral, troca de óleo, freios e revisão completa para seu veículo.',
    tags: ['oficina', 'carro', 'manutenção'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 98888-1111',
    badge: '',
  },
  {
    id: 15,
    titulo: 'Loja de Roupas Estilo Urbano',
    cat: 'Comércio',
    preco: 'A partir de R$ 49,90',
    desc: 'Moda masculina e feminina com peças modernas e preços acessíveis.',
    tags: ['roupa', 'moda', 'estilo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 99999-1111',
    badge: 'Novo',
  },
  {
    id: 16,
    titulo: 'Academia Nova Europa Fitness',
    cat: 'Serviços',
    preco: 'A partir de R$ 79,90/mês',
    desc: 'Academia completa com musculação, personal trainer e aulas funcionais.',
    tags: ['academia', 'fitness', 'saúde'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-1111',
    badge: '',
  },
  {
    id: 17,
    titulo: 'Açougue Nova Europa',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Carnes frescas, cortes especiais e atendimento personalizado.',
    tags: ['açougue', 'carne', 'alimentos'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0001',
    badge: '',
  },
  {
    id: 18,
    titulo: 'Hortifruti Verde Vida',
    cat: 'Comércio',
    preco: 'A partir de R$ 3,00',
    desc: 'Frutas, verduras e legumes frescos direto do produtor.',
    tags: ['hortifruti', 'saudável', 'orgânico'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0002',
    badge: '',
  },
  {
    id: 19,
    titulo: 'Casa de Ração Animal Feliz',
    cat: 'Comércio',
    preco: 'A partir de R$ 25,00',
    desc: 'Rações e acessórios para cães, gatos e aves.',
    tags: ['pet', 'ração', 'animais'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0003',
    badge: '',
  },
  {
    id: 20,
    titulo: 'Papelaria Nova Europa',
    cat: 'Comércio',
    preco: 'A partir de R$ 2,00',
    desc: 'Material escolar, escritório e papelaria completa.',
    tags: ['papelaria', 'escola', 'escritório'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0004',
    badge: '',
  },
  {
    id: 21,
    titulo: 'Loja de Utilidades do Lar',
    cat: 'Comércio',
    preco: 'A partir de R$ 10,00',
    desc: 'Utensílios domésticos, cozinha e decoração.',
    tags: ['casa', 'utilidades', 'decoração'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0005',
    badge: '',
  },
  {
    id: 22,
    titulo: 'Sorveteria Doce Gelato',
    cat: 'Comércio',
    preco: 'A partir de R$ 8,00',
    desc: 'Sorvetes artesanais e açaí com diversos acompanhamentos.',
    tags: ['sorvete', 'açaí', 'doce'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0006',
    badge: 'Popular',
  },
  {
    id: 23,
    titulo: 'Chaveiro Rápido 24h',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Abertura de portas, cópia de chaves e atendimento emergencial.',
    tags: ['chaveiro', '24h', 'urgente'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0007',
    badge: '24h',
  },
  {
    id: 24,
    titulo: 'Lavanderia Lava Fácil',
    cat: 'Serviços',
    preco: 'A partir de R$ 15,00',
    desc: 'Lavagem e secagem de roupas com qualidade e rapidez.',
    tags: ['lavanderia', 'roupa', 'limpeza'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0008',
    badge: '',
  },
  {
    id: 25,
    titulo: 'Borracharia Nova Europa',
    cat: 'Serviços',
    preco: 'A partir de R$ 20,00',
    desc: 'Conserto e troca de pneus com atendimento rápido.',
    tags: ['pneu', 'carro', 'borracharia'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0009',
    badge: '',
  },
  {
    id: 26,
    titulo: 'Distribuidora de Bebidas Nova Europa',
    cat: 'Comércio',
    preco: 'A partir de R$ 5,00',
    desc: 'Bebidas em geral com entrega rápida no bairro.',
    tags: ['bebidas', 'delivery', 'festa'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0010',
    badge: '',
  },
  {
    id: 27,
    titulo: 'Loja de Celulares Conecta',
    cat: 'Comércio',
    preco: 'A partir de R$ 100,00',
    desc: 'Venda de celulares, acessórios e assistência técnica.',
    tags: ['celular', 'tecnologia', 'assistência'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0011',
    badge: '',
  },
  {
    id: 28,
    titulo: 'Gráfica Rápida Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Impressões, cartões de visita e serviços gráficos em geral.',
    tags: ['gráfica', 'impressão', 'design'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0012',
    badge: '',
  },
  {
    id: 29,
    titulo: 'Assistência Técnica EletroFix',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Conserto de eletrodomésticos e eletrônicos.',
    tags: ['assistência', 'eletrônicos', 'reparo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0013',
    badge: '',
  },
  {
    id: 30,
    titulo: 'Floricultura Jardim & Amor',
    cat: 'Comércio',
    preco: 'A partir de R$ 20,00',
    desc: 'Flores, arranjos e presentes para todas as ocasiões.',
    tags: ['flores', 'presentes', 'decoração'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0014',
    badge: '',
  },
  {
    id: 31,
    titulo: 'Loja de Calçados Passo Firme',
    cat: 'Comércio',
    preco: 'A partir de R$ 79,90',
    desc: 'Calçados masculinos, femininos e infantis.',
    tags: ['calçados', 'sapatos', 'moda'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0015',
    badge: '',
  },
  {
    id: 32,
    titulo: 'Barbearia Estilo Fino',
    cat: 'Serviços',
    preco: 'A partir de R$ 25,00',
    desc: 'Cortes modernos, barba e atendimento diferenciado.',
    tags: ['barbearia', 'corte', 'estilo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0016',
    badge: '',
  },
  {
    id: 33,
    titulo: 'Restaurante Sabor do Bairro',
    cat: 'Comércio',
    preco: 'A partir de R$ 20,00',
    desc: 'Almoço caseiro com marmitas e pratos feitos.',
    tags: ['restaurante', 'almoço', 'comida'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0017',
    badge: '',
  },
  {
    id: 34,
    titulo: 'Depósito de Gás Nova Europa',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Venda e entrega de gás de cozinha no bairro.',
    tags: ['gás', 'entrega', 'cozinha'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0018',
    badge: '',
  },
  {
    id: 35,
    titulo: 'Loja de Bicicletas Pedal Livre',
    cat: 'Comércio',
    preco: 'A partir de R$ 300,00',
    desc: 'Venda e manutenção de bicicletas e acessórios.',
    tags: ['bicicleta', 'esporte', 'manutenção'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0019',
    badge: '',
  },
  {
    id: 36,
    titulo: 'Studio Fotográfico Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Ensaios fotográficos, eventos e fotos profissionais.',
    tags: ['foto', 'evento', 'ensaio'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0020',
    badge: '',
  },
  {
    id: 37,
    titulo: 'Doceria Doce Encanto',
    cat: 'Comércio',
    preco: 'A partir de R$ 6,00',
    desc: 'Doces artesanais, bolos e sobremesas para todas as ocasiões.',
    tags: ['doces', 'bolo', 'sobremesa'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0021',
    badge: '',
  },
  {
    id: 38,
    titulo: 'Casa de Tintas ColorMax',
    cat: 'Comércio',
    preco: 'A partir de R$ 50,00',
    desc: 'Tintas residenciais, automotivas e acessórios para pintura.',
    tags: ['tintas', 'pintura', 'reforma'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0022',
    badge: '',
  },
  {
    id: 39,
    titulo: 'Vidraçaria Transparente',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Vidros, espelhos e box para banheiro sob medida.',
    tags: ['vidro', 'box', 'espelho'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0023',
    badge: '',
  },
  {
    id: 40,
    titulo: 'Loja de Informática TechNova',
    cat: 'Comércio',
    preco: 'A partir de R$ 100,00',
    desc: 'Computadores, periféricos e assistência técnica especializada.',
    tags: ['informática', 'pc', 'tecnologia'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0024',
    badge: '',
  },
  {
    id: 41,
    titulo: 'Clínica Odontológica Sorriso',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Atendimento odontológico completo com profissionais qualificados.',
    tags: ['dentista', 'saúde', 'clínica'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0025',
    badge: '',
  },
  {
    id: 42,
    titulo: 'Ótica Visão Clara',
    cat: 'Comércio',
    preco: 'A partir de R$ 120,00',
    desc: 'Óculos de grau, solares e exames de vista.',
    tags: ['óculos', 'visão', 'saúde'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0026',
    badge: '',
  },
  {
    id: 43,
    titulo: 'Loja de Materiais Elétricos Luz & Cia',
    cat: 'Comércio',
    preco: 'A partir de R$ 10,00',
    desc: 'Fios, cabos, lâmpadas e materiais elétricos em geral.',
    tags: ['elétrica', 'material', 'obra'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0027',
    badge: '',
  },
  {
    id: 44,
    titulo: 'Buffet Festa Feliz',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Buffet completo para festas e eventos no bairro.',
    tags: ['festa', 'buffet', 'evento'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0028',
    badge: '',
  },
  {
    id: 45,
    titulo: 'Loja de Cosméticos Bella',
    cat: 'Comércio',
    preco: 'A partir de R$ 15,00',
    desc: 'Produtos de beleza, maquiagem e cuidados pessoais.',
    tags: ['cosméticos', 'beleza', 'maquiagem'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0029',
    badge: '',
  },
  {
    id: 46,
    titulo: 'Casa de Bolos Caseiros',
    cat: 'Comércio',
    preco: 'A partir de R$ 25,00',
    desc: 'Bolos frescos e receitas caseiras todos os dias.',
    tags: ['bolo', 'caseiro', 'doces'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0030',
    badge: '',
  },
  {
    id: 47,
    titulo: 'Distribuidora Água & Gás',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Entrega de água mineral e gás de cozinha.',
    tags: ['água', 'gás', 'delivery'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0031',
    badge: '',
  },
  {
    id: 48,
    titulo: 'Studio de Pilates Equilíbrio',
    cat: 'Serviços',
    preco: 'A partir de R$ 90,00/mês',
    desc: 'Aulas de pilates para saúde e bem-estar.',
    tags: ['pilates', 'saúde', 'fitness'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0032',
    badge: '',
  },
  {
    id: 49,
    titulo: 'Loja de Móveis Planejados',
    cat: 'Comércio',
    preco: 'Sob consulta',
    desc: 'Projetos personalizados para sua casa ou escritório.',
    tags: ['móveis', 'planejados', 'decoração'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0033',
    badge: '',
  },
  {
    id: 50,
    titulo: 'Escola de Idiomas Nova Europa',
    cat: 'Serviços',
    preco: 'A partir de R$ 120,00/mês',
    desc: 'Cursos de inglês e espanhol para todas as idades.',
    tags: ['idiomas', 'inglês', 'curso'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0034',
    badge: '',
  },
  {
    id: 51,
    titulo: 'Loja de Esportes Ativa',
    cat: 'Comércio',
    preco: 'A partir de R$ 30,00',
    desc: 'Roupas e acessórios esportivos para diversas modalidades.',
    tags: ['esporte', 'fitness', 'roupas'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0035',
    badge: '',
  },
  {
    id: 52,
    titulo: 'Serviço de Limpeza Residencial',
    cat: 'Serviços',
    preco: 'A partir de R$ 100,00',
    desc: 'Limpeza completa de casas e apartamentos.',
    tags: ['limpeza', 'casa', 'serviço'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0036',
    badge: '',
  },
  {
    id: 53,
    titulo: 'Loja de Artigos Religiosos Fé Viva',
    cat: 'Comércio',
    preco: 'A partir de R$ 10,00',
    desc: 'Bíblias, presentes e artigos religiosos.',
    tags: ['fé', 'religioso', 'bíblia'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0037',
    badge: '',
  },
  {
    id: 54,
    titulo: 'Consultoria de TI Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Suporte técnico, redes e segurança da informação.',
    tags: ['ti', 'suporte', 'segurança'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0038',
    badge: '',
  },
  {
    id: 55,
    titulo: 'Loja de Brinquedos Alegria',
    cat: 'Comércio',
    preco: 'A partir de R$ 20,00',
    desc: 'Brinquedos educativos e diversão para todas as idades.',
    tags: ['brinquedo', 'criança', 'diversão'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0039',
    badge: '',
  },
  {
    id: 56,
    titulo: 'Estúdio de Tatuagem Arte Viva',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Tatuagens personalizadas com profissionais experientes.',
    tags: ['tatuagem', 'arte', 'estúdio'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0040',
    badge: '',
  },
  {
    id: 57,
    titulo: 'Lanchonete Sabor da Esquina',
    cat: 'Comércio',
    preco: 'A partir de R$ 12,00',
    desc: 'Lanches artesanais, hambúrgueres e porções com entrega rápida.',
    tags: ['lanche', 'hambúrguer', 'delivery'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0041',
    badge: '',
  },
  {
    id: 58,
    titulo: 'Oficina Mecânica Motor Forte',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Manutenção geral, revisão e diagnóstico automotivo.',
    tags: ['oficina', 'carro', 'manutenção'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0042',
    badge: '',
  },
  {
    id: 59,
    titulo: 'Lanchonete Grill Burguer',
    cat: 'Comércio',
    preco: 'A partir de R$ 15,00',
    desc: 'Hambúrguer na brasa, combos e bebidas geladas.',
    tags: ['burger', 'lanche', 'combo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0043',
    badge: 'Popular',
  },
  {
    id: 60,
    titulo: 'Auto Center Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Alinhamento, balanceamento e troca de óleo.',
    tags: ['auto', 'revisão', 'óleo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0044',
    badge: '',
  },
  {
    id: 61,
    titulo: 'Lanchonete Top Lanches',
    cat: 'Comércio',
    preco: 'A partir de R$ 10,00',
    desc: 'Hot dog, X-salada e sucos naturais.',
    tags: ['hotdog', 'lanche', 'rápido'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0045',
    badge: '',
  },
  {
    id: 62,
    titulo: 'Mecânica Rápida Express',
    cat: 'Serviços',
    preco: 'A partir de R$ 80,00',
    desc: 'Serviços rápidos com agilidade e preço justo.',
    tags: ['mecânica', 'rápido', 'carro'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0046',
    badge: '',
  },
  {
    id: 63,
    titulo: 'Lanchonete Point do Açaí',
    cat: 'Comércio',
    preco: 'A partir de R$ 8,00',
    desc: 'Açaí, smoothies e lanches leves.',
    tags: ['açaí', 'saudável', 'lanche'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0047',
    badge: '',
  },
  {
    id: 64,
    titulo: 'Oficina Mecânica Elite Car',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Especializada em veículos nacionais e importados.',
    tags: ['carro', 'importado', 'oficina'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0048',
    badge: '',
  },
  {
    id: 65,
    titulo: 'Lanchonete Família Lanches',
    cat: 'Comércio',
    preco: 'A partir de R$ 13,00',
    desc: 'Ambiente familiar com lanches e porções variadas.',
    tags: ['família', 'lanche', 'porções'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0049',
    badge: '',
  },
  {
    id: 66,
    titulo: 'Auto Mecânica Confiança',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Reparos mecânicos com garantia e confiança.',
    tags: ['mecânica', 'confiança', 'carro'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0050',
    badge: '',
  },
  {
    id: 67,
    titulo: 'Lanchonete Mega Burguer',
    cat: 'Comércio',
    preco: 'A partir de R$ 18,00',
    desc: 'Hambúrgueres grandes e combos especiais.',
    tags: ['burger', 'combo', 'lanche'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0051',
    badge: '',
  },
  {
    id: 68,
    titulo: 'Oficina Turbo Car',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Especializada em motores e desempenho.',
    tags: ['motor', 'turbo', 'performance'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0052',
    badge: '',
  },
  {
    id: 69,
    titulo: 'Lanchonete Sabor na Chapa',
    cat: 'Comércio',
    preco: 'A partir de R$ 14,00',
    desc: 'Lanches feitos na hora com ingredientes frescos.',
    tags: ['chapa', 'lanche', 'rápido'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0053',
    badge: '',
  },
  {
    id: 70,
    titulo: 'Mecânica do Bairro',
    cat: 'Serviços',
    preco: 'A partir de R$ 70,00',
    desc: 'Serviços mecânicos com preço acessível.',
    tags: ['bairro', 'carro', 'reparo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0054',
    badge: '',
  },
  {
    id: 71,
    titulo: 'Lanchonete Delícia Express',
    cat: 'Comércio',
    preco: 'A partir de R$ 11,00',
    desc: 'Lanches rápidos com entrega no bairro.',
    tags: ['delivery', 'lanche', 'rápido'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0055',
    badge: '',
  },
  {
    id: 72,
    titulo: 'Oficina Mecânica Auto Prime',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Serviços premium com equipamentos modernos.',
    tags: ['premium', 'auto', 'revisão'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0056',
    badge: '',
  },
  {
    id: 73,
    titulo: 'Lanchonete Rei do X',
    cat: 'Comércio',
    preco: 'A partir de R$ 16,00',
    desc: 'Especializada em X-tudo e lanches completos.',
    tags: ['xtudo', 'lanche', 'burger'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0057',
    badge: '',
  },
  {
    id: 74,
    titulo: 'Mecânica Nova Geração',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Tecnologia moderna para diagnóstico automotivo.',
    tags: ['tecnologia', 'carro', 'scanner'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0058',
    badge: '',
  },
  {
    id: 75,
    titulo: 'Lanchonete Sabor & Grill',
    cat: 'Comércio',
    preco: 'A partir de R$ 17,00',
    desc: 'Lanches e carnes na grelha com sabor único.',
    tags: ['grill', 'lanche', 'carne'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0059',
    badge: '',
  },
  {
    id: 76,
    titulo: 'Auto Mecânica Expert Car',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Especialistas em manutenção preventiva.',
    tags: ['preventiva', 'carro', 'oficina'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0060',
    badge: '',
  },
  {
    id: 77,
    titulo: 'Lanchonete Happy Burguer',
    cat: 'Comércio',
    preco: 'A partir de R$ 15,00',
    desc: 'Ambiente descontraído com lanches e bebidas.',
    tags: ['burger', 'lanche', 'happy'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0061',
    badge: '',
  },
  {
    id: 78,
    titulo: 'Oficina Mecânica União',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Serviços completos com equipe experiente.',
    tags: ['oficina', 'equipe', 'carro'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0062',
    badge: '',
  },
  {
    id: 79,
    titulo: 'Lanchonete Central Lanches',
    cat: 'Comércio',
    preco: 'A partir de R$ 12,00',
    desc: 'Lanches rápidos com ótimo custo-benefício.',
    tags: ['lanche', 'barato', 'rápido'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0063',
    badge: '',
  },
  {
    id: 80,
    titulo: 'Mecânica Auto Service',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Revisão completa e serviços automotivos.',
    tags: ['service', 'carro', 'manutenção'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0064',
    badge: '',
  },
  {
    id: 81,
    titulo: 'Lanchonete Express Burguer',
    cat: 'Comércio',
    preco: 'A partir de R$ 14,00',
    desc: 'Lanches rápidos e saborosos para o dia a dia.',
    tags: ['lanche', 'express', 'burger'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0065',
    badge: '',
  },
  {
    id: 82,
    titulo: 'Oficina Mecânica Car Master',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Especialistas em mecânica geral e elétrica.',
    tags: ['carro', 'elétrica', 'oficina'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0066',
    badge: '',
  },
  {
    id: 83,
    titulo: 'Lanchonete Sabor da Noite',
    cat: 'Comércio',
    preco: 'A partir de R$ 13,00',
    desc: 'Lanches noturnos com entrega rápida.',
    tags: ['noite', 'lanche', 'delivery'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0067',
    badge: '',
  },
  {
    id: 84,
    titulo: 'Auto Mecânica Speed Car',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Serviços rápidos com qualidade e confiança.',
    tags: ['speed', 'carro', 'oficina'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0068',
    badge: '',
  },
  {
    id: 85,
    titulo: 'Lanchonete Mix Lanches',
    cat: 'Comércio',
    preco: 'A partir de R$ 11,00',
    desc: 'Variedade de lanches e bebidas.',
    tags: ['mix', 'lanche', 'variedade'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0069',
    badge: '',
  },
  {
    id: 86,
    titulo: 'Oficina Mecânica Total Car',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Serviços completos para seu veículo.',
    tags: ['total', 'carro', 'oficina'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 91111-0070',
    badge: '',
  },

  {
    id: 87,
    titulo: 'Supermercado Pague Menos',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Supermercado completo com hortifruti, açougue e produtos do dia a dia.',
    tags: ['mercado', 'supermercado', 'alimentos'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0101',
    badge: '',
  },
  {
    id: 88,
    titulo: 'Supermercado Shimozono',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Mercado tradicional com variedade e bom atendimento.',
    tags: ['mercado', 'alimentos', 'bairro'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0102',
    badge: '',
  },
  {
    id: 89,
    titulo: 'Sacolão Nova Europa',
    cat: 'Comércio',
    preco: 'A partir de R$ 3,00',
    desc: 'Frutas, verduras e legumes frescos diariamente.',
    tags: ['hortifruti', 'saudável', 'feira'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0103',
    badge: '',
  },
  {
    id: 90,
    titulo: 'Pizzaria Nova Europa',
    cat: 'Comércio',
    preco: 'A partir de R$ 35,00',
    desc: 'Pizzas tradicionais e especiais com entrega rápida.',
    tags: ['pizza', 'delivery', 'jantar'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0104',
    badge: 'Popular',
  },
  {
    id: 91,
    titulo: 'Restaurante Bom Prato Nova Europa',
    cat: 'Comércio',
    preco: 'A partir de R$ 1,00',
    desc: 'Refeições acessíveis com qualidade e apoio social.',
    tags: ['restaurante', 'popular', 'almoço'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0105',
    badge: '',
  },
  {
    id: 92,
    titulo: 'Padaria Baden',
    cat: 'Comércio',
    preco: 'A partir de R$ 5,00',
    desc: 'Pães frescos, doces e café da manhã completo.',
    tags: ['padaria', 'café', 'pães'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0106',
    badge: '',
  },
  {
    id: 93,
    titulo: 'Drogal Baden Powell',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Medicamentos, perfumaria e produtos de saúde.',
    tags: ['farmácia', 'saúde', 'remédio'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0107',
    badge: '',
  },
  {
    id: 94,
    titulo: 'Drogasil Nova Europa',
    cat: 'Comércio',
    preco: 'Consulte no local',
    desc: 'Rede de farmácia com atendimento rápido e variedade.',
    tags: ['farmácia', 'remédios', 'rede'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0108',
    badge: '',
  },
  {
    id: 95,
    titulo: 'Nova Europa Materiais para Construção',
    cat: 'Comércio',
    preco: 'Sob consulta',
    desc: 'Materiais completos para construção e reforma.',
    tags: ['construção', 'obra', 'material'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0109',
    badge: '',
  },
  {
    id: 96,
    titulo: 'Madeireira Nova Europa',
    cat: 'Comércio',
    preco: 'Sob consulta',
    desc: 'Madeiras e acessórios para construção e móveis.',
    tags: ['madeira', 'obra', 'móveis'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0110',
    badge: '',
  },
  {
    id: 97,
    titulo: 'Assistência Técnica Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Conserto de eletrônicos e equipamentos.',
    tags: ['assistência', 'técnico', 'reparo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0111',
    badge: '',
  },
  {
    id: 98,
    titulo: 'Salão Nova Europa',
    cat: 'Serviços',
    preco: 'A partir de R$ 30,00',
    desc: 'Cortes, coloração e cuidados com o cabelo.',
    tags: ['beleza', 'cabelo', 'salão'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0112',
    badge: '',
  },
  {
    id: 99,
    titulo: 'Barbearia Baden',
    cat: 'Serviços',
    preco: 'A partir de R$ 25,00',
    desc: 'Cortes masculinos e barba com estilo.',
    tags: ['barbearia', 'corte', 'estilo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0113',
    badge: '',
  },
  {
    id: 100,
    titulo: 'Oficina Mecânica Baden',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Manutenção automotiva completa.',
    tags: ['oficina', 'carro', 'reparo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0114',
    badge: '',
  },
  {
    id: 101,
    titulo: 'Auto Center Baden',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Alinhamento, balanceamento e revisão.',
    tags: ['auto', 'revisão', 'carro'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0115',
    badge: '',
  },
  {
    id: 102,
    titulo: 'Pet Shop Nova Europa',
    cat: 'Comércio',
    preco: 'A partir de R$ 20,00',
    desc: 'Produtos e cuidados para seu pet.',
    tags: ['pet', 'ração', 'banho'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0116',
    badge: '',
  },
  {
    id: 103,
    titulo: 'Clínica Veterinária Baden',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Atendimento veterinário completo.',
    tags: ['veterinário', 'pet', 'saúde'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0117',
    badge: '',
  },
  {
    id: 104,
    titulo: 'Escola Infantil Nova Europa',
    cat: 'Serviços',
    preco: 'Sob consulta',
    desc: 'Educação infantil com qualidade e cuidado.',
    tags: ['escola', 'educação', 'criança'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0118',
    badge: '',
  },
  {
    id: 105,
    titulo: 'Curso de Inglês Baden',
    cat: 'Serviços',
    preco: 'A partir de R$ 120,00/mês',
    desc: 'Cursos de inglês para todas as idades.',
    tags: ['inglês', 'curso', 'idioma'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0119',
    badge: '',
  },
  {
    id: 106,
    titulo: 'Lotérica Nova Europa',
    cat: 'Serviços',
    preco: 'Consulte no local',
    desc: 'Pagamentos, jogos e serviços bancários.',
    tags: ['lotérica', 'pagamento', 'banco'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0120',
    badge: '',
  },
  {
    id: 107,
    titulo: 'Restaurante Nova Europa Grill',
    cat: 'Alimentação',
    preco: 'A partir de R$ 25,00',
    desc: 'Self-service com comida caseira e churrasco todos os dias.',
    tags: ['restaurante', 'self-service', 'almoço'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0201',
    badge: '',
  },
  {
    id: 108,
    titulo: 'Restaurante Sabor da Vila',
    cat: 'Alimentação',
    preco: 'A partir de R$ 28,00',
    desc: 'Pratos à la carte com sabor caseiro.',
    tags: ['restaurante', 'alacarte', 'jantar'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0202',
    badge: '',
  },
  {
    id: 109,
    titulo: 'Lanchonete Nova Europa Express',
    cat: 'Alimentação',
    preco: 'A partir de R$ 12,00',
    desc: 'Lanches rápidos com entrega no bairro.',
    tags: ['lanche', 'rápido', 'delivery'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0203',
    badge: '',
  },
  {
    id: 110,
    titulo: 'Pizzaria Sabor Italiano',
    cat: 'Alimentação',
    preco: 'A partir de R$ 39,90',
    desc: 'Pizzas artesanais com massa fina e crocante.',
    tags: ['pizza', 'delivery', 'jantar'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0204',
    badge: 'Popular',
  },
  {
    id: 111,
    titulo: 'Hamburgueria Prime Burguer',
    cat: 'Alimentação',
    preco: 'A partir de R$ 18,00',
    desc: 'Hambúrguer artesanal com ingredientes premium.',
    tags: ['burger', 'artesanal', 'lanche'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0205',
    badge: '',
  },
  {
    id: 112,
    titulo: 'Marmitaria Caseira Nova Europa',
    cat: 'Alimentação',
    preco: 'A partir de R$ 15,00',
    desc: 'Marmitas com comida caseira e entrega rápida.',
    tags: ['marmita', 'caseira', 'delivery'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0206',
    badge: '',
  },
  {
    id: 113,
    titulo: 'Padaria Pão Quente',
    cat: 'Alimentação',
    preco: 'A partir de R$ 5,00',
    desc: 'Pães frescos, bolos e café da manhã completo.',
    tags: ['padaria', 'pães', 'café'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0207',
    badge: '',
  },
  {
    id: 114,
    titulo: 'Cafeteria Aroma Café',
    cat: 'Alimentação',
    preco: 'A partir de R$ 7,00',
    desc: 'Cafés especiais, doces e ambiente aconchegante.',
    tags: ['café', 'cafeteria', 'doces'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0208',
    badge: '',
  },
  {
    id: 115,
    titulo: 'Food Truck Burguer Station',
    cat: 'Alimentação',
    preco: 'A partir de R$ 16,00',
    desc: 'Food truck com hambúrgueres e batatas especiais.',
    tags: ['foodtruck', 'burger', 'rua'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0209',
    badge: '',
  },
  {
    id: 116,
    titulo: 'Doceria Doce Sabor',
    cat: 'Alimentação',
    preco: 'A partir de R$ 6,00',
    desc: 'Doces, bolos e sobremesas artesanais.',
    tags: ['doces', 'bolo', 'sobremesa'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0210',
    badge: '',
  },
  {
    id: 117,
    titulo: 'Restaurante Buffet Nova Europa',
    cat: 'Alimentação',
    preco: 'A partir de R$ 30,00',
    desc: 'Buffet completo com variedade de pratos.',
    tags: ['buffet', 'almoço', 'restaurante'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0211',
    badge: '',
  },
  {
    id: 118,
    titulo: 'Hamburgueria Smash Burguer',
    cat: 'Alimentação',
    preco: 'A partir de R$ 20,00',
    desc: 'Smash burgers com sabor intenso.',
    tags: ['smash', 'burger', 'lanche'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0212',
    badge: '',
  },
  {
    id: 119,
    titulo: 'Pizzaria Express Nova Europa',
    cat: 'Alimentação',
    preco: 'A partir de R$ 34,90',
    desc: 'Pizzas rápidas com entrega eficiente.',
    tags: ['pizza', 'rápido', 'delivery'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0213',
    badge: '',
  },
  {
    id: 120,
    titulo: 'Marmitaria Fit Saúde',
    cat: 'Alimentação',
    preco: 'A partir de R$ 18,00',
    desc: 'Marmitas fitness com opções saudáveis.',
    tags: ['fit', 'saudável', 'marmita'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0214',
    badge: '',
  },
  {
    id: 121,
    titulo: 'Padaria & Café Nova Europa',
    cat: 'Alimentação',
    preco: 'A partir de R$ 6,00',
    desc: 'Padaria com espaço para café e lanches.',
    tags: ['padaria', 'café', 'lanche'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0215',
    badge: '',
  },
  {
    id: 122,
    titulo: 'Cafeteria Premium Coffee',
    cat: 'Alimentação',
    preco: 'A partir de R$ 9,00',
    desc: 'Cafés especiais e doces gourmet.',
    tags: ['café', 'premium', 'doces'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0216',
    badge: '',
  },
  {
    id: 123,
    titulo: 'Food Truck Espetinho Grill',
    cat: 'Alimentação',
    preco: 'A partir de R$ 10,00',
    desc: 'Espetinhos variados e bebidas.',
    tags: ['espetinho', 'foodtruck', 'noite'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0217',
    badge: '',
  },
  {
    id: 124,
    titulo: 'Confeitaria Delícia de Bairro',
    cat: 'Alimentação',
    preco: 'A partir de R$ 8,00',
    desc: 'Bolos personalizados e doces finos.',
    tags: ['confeitaria', 'bolo', 'doces'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0218',
    badge: '',
  },
  {
    id: 125,
    titulo: 'Restaurante Caseiro da Dona Ana',
    cat: 'Alimentação',
    preco: 'A partir de R$ 22,00',
    desc: 'Comida caseira com sabor de casa.',
    tags: ['caseiro', 'almoço', 'restaurante'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0219',
    badge: '',
  },
  {
    id: 126,
    titulo: 'Lanchonete Mix Burguer',
    cat: 'Alimentação',
    preco: 'A partir de R$ 14,00',
    desc: 'Variedade de lanches e combos.',
    tags: ['lanche', 'burger', 'combo'],
    local: 'Jardim Nova Europa, Campinas/SP',
    contato: '(19) 90000-0220',
    badge: '',
  },
]

dados.sort((a, b) => {
  const badgeA = (a.badge || '').trim()
  const badgeB = (b.badge || '').trim()

  const badgeALower = badgeA.toLowerCase()
  const badgeBLower = badgeB.toLowerCase()

  // 1. "Destaque" primeiro
  // if (badgeALower === 'destaque' && badgeBLower !== 'destaque') return -1
  // if (badgeALower !== 'destaque' && badgeBLower === 'destaque') return 1

  // 2. Não-vazios antes dos vazios
  if (badgeA && !badgeB) return -1
  if (!badgeA && badgeB) return 1

  // 3. Números antes de letras
  const aIsNum = /^[0-9]/.test(badgeALower)
  const bIsNum = /^[0-9]/.test(badgeBLower)

  if (aIsNum && !bIsNum) return -1
  if (!aIsNum && bIsNum) return 1

  // 4. Ordem alfabética ou numérica entre eles
  return badgeALower.localeCompare(badgeBLower)
})

let filtrado = [...dados]
let searchTerm = ''

function highlight(text, term) {
  if (!term) return text
  const re = new RegExp(
    `(${term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`,
    'gi'
  )
  return text.replace(re, '<mark>$1</mark>')
}

function renderGrid(items) {
  const grid = document.getElementById('grid')
  const label = document.getElementById('sectionLabel')
  label.textContent = searchTerm
    ? `${items.length} resultado${items.length !== 1 ? 's' : ''} para "${searchTerm}"`
    : 'Todos os anúncios'

  if (!items.length) {
    grid.innerHTML = `<div class="empty-state"><div class="big">🔍</div><p>Nenhum classificado encontrado para "<strong>${searchTerm}</strong>"</p></div>`
    return
  }

  // <div class="card-footer">
  // </div>

  grid.innerHTML = items
    .map(
      (d, i) => `
    <div class="card" style="animation-delay:${i * 0.06}s" onclick="openCard(${d.id})">
      ${d.badge ? `<span class="card-badge">${d.badge}</span>` : ''}
      <div class="card-category">${d.cat}</div>
      <div class="card-title">${highlight(d.titulo, searchTerm)}</div>
      <div class="card-desc">${highlight(d.desc.substring(0, 90) + '…', searchTerm)}</div>
        <span class="card-price">${d.preco}</span>
        <span class="card-contact">📍 ${d.local.split(',')[0]}</span>
    </div>
  `
    )
    .join('')
}

function doSearch() {
  searchTerm = document.getElementById('searchInput').value.trim()
  if (!searchTerm) {
    filtrado = [...dados]
  } else {
    const q = searchTerm.toLowerCase()
    filtrado = dados.filter(
      (d) =>
        d.titulo.toLowerCase().includes(q) ||
        d.desc.toLowerCase().includes(q) ||
        d.cat.toLowerCase().includes(q) ||
        d.tags.some((t) => t.toLowerCase().includes(q))
    )
  }
  renderGrid(filtrado)
}

document.getElementById('searchInput').addEventListener('input', doSearch)
document.getElementById('searchInput').addEventListener('keydown', (e) => {
  if (e.key === 'Enter') doSearch()
})

function openCard(id) {
  const d = dados.find((x) => x.id === id)
  if (!d) return
  document.getElementById('mCat').textContent = d.cat
  document.getElementById('mTitle').textContent = d.titulo
  document.getElementById('mPrice').textContent = d.preco
  document.getElementById('mDesc').textContent = d.desc
  document.getElementById('mTags').innerHTML = d.tags
    .map((t) => `<span class="tag">${t}</span>`)
    .join('')
  document.getElementById('mInfo').innerHTML = `
    <div class="info-item"><div class="info-label">Localização</div><div class="info-val">${d.local}</div></div>
    <div class="info-item"><div class="info-label">Contato</div><div class="info-val">${d.contato}</div></div>
    <div class="info-item"><div class="info-label">Categoria</div><div class="info-val">${d.cat}</div></div>
    <div class="info-item"><div class="info-label">Anúncio Nº</div><div class="info-val">#${String(d.id).padStart(4, '0')}</div></div>
  `
  document.getElementById('mContact').textContent = `Contatar: ${d.contato}`
  openOverlay('viewOverlay')
}

function openOverlay(id) {
  document.getElementById(id).classList.add('active')
}
function closeOverlay(id) {
  document.getElementById(id).classList.remove('active')
}

function closeViewModal(e) {
  if (e.target === document.getElementById('viewOverlay'))
    closeOverlay('viewOverlay')
}
function closeViewModal2(e) {
  if (e.target === document.getElementById('addOverlay'))
    closeOverlay('addOverlay')
}

function openAddModal() {
  openOverlay('addOverlay')
}

function addClassificado() {
  const titulo = document.getElementById('fTitle').value.trim()
  const cat = document.getElementById('fCat').value
  const preco = document.getElementById('fPrice').value
  const desc = document.getElementById('fDesc').value.trim()
  const contato = document.getElementById('fContact').value.trim()
  const local = document.getElementById('fLocal').value.trim()
  const tagsStr = document.getElementById('fTags').value.trim()

  if (!titulo || !desc) {
    alert('Preencha ao menos o título e a descrição.')
    return
  }

  const novoId = dados.length ? Math.max(...dados.map((d) => d.id)) + 1 : 1
  dados.unshift({
    id: novoId,
    titulo,
    cat,
    preco: preco
      ? `R$ ${parseFloat(preco).toFixed(2).replace('.', ',')}`
      : 'Sob consulta',
    desc,
    tags: tagsStr
      ? tagsStr
          .split(',')
          .map((t) => t.trim())
          .filter(Boolean)
      : [],
    local: local || 'Brasil',
    contato: contato || 'Não informado',
    badge: 'Novo',
  })

  // clear form
  ;['fTitle', 'fPrice', 'fDesc', 'fContact', 'fLocal', 'fTags'].forEach(
    (id) => (document.getElementById(id).value = '')
  )
  closeOverlay('addOverlay')
  searchTerm = ''
  document.getElementById('searchInput').value = ''
  filtrado = [...dados]
  renderGrid(filtrado)
}

renderGrid(dados)
